config/routes.rb
Gondi::Application.routes.draw do |map|

  devise_for :admins
  devise_for :users

  resources :athletes

  match 'favorite/:id' => 'favorites#toggle', :as => 'favorite'
  match 'saves' => 'favorites#index', :as => 'favorites'

  match 'watch/:id' => 'videos#show', :as => 'watch_video'
  match 'videos/add_athlete' => 'videos#add_athlete'
  match 'submit_link' => 'videos#submit_link', :as => 'submit_link'
  resources :videos

  match 'admin', :to => 'admin#index', :as => 'admin_root'

  root :to => 'welcome#index'
  match 'info' => 'welcome#info', :as => 'info'

end

app/models/video.rb
class Video < ActiveRecord::Base

  has_attached_file :snapshot, :styles => { :thumb => "144x108>" }
  has_friendly_id :title, :use_slug => true

  has_and_belongs_to_many :athletes
  has_many :favorites, :dependent => :destroy
  has_many :user_favorites, :through => :favorites, :source => :user

  has_many :views, :dependent => :destroy
  has_many :user_views, :through => :views, :source => :user

  default_scope :order => 'videos.published_at DESC'
  scope :active, where("status = ? AND published_at <= ?", 'active', Time.now)

  def related_athletes=(athlete_names)
    # create a list of all existing athletes
    diff = athletes.map(&:name)
    athlete_names.each do |name|
      # see if an existing athlete exists, if not create one
      athlete = Athlete.find_or_create_by_name(name)
      unless athletes.include? athlete
        # add athlete to athletes
        athletes << athlete
      else
        # remove athlete from diff list
        diff.delete_if { |a| a == athlete.name }
      end
    end
    # delete all athletes that are no longer related
    athletes.delete(Athlete.find_all_by_name(diff))
  end

  def total_views
    views.map(&:total).sum
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  respond_to :html, :js

  def index
    @videos = Video.active
  end

  def show
    @video = Video.find params[:id]
    @selector = '.video_'+@video.id.to_s
    current_user.track_view(@video) if current_user

    respond_to do |format|
      format.html {
        @title = 'Videos'
        @videos = current_admin ? Video.all : Video.active }
      format.js
    end
  end

  def new
    @video = Video.new
  end

  def submit_link
    @video = Video.new
  end

  def edit
    @video = Video.find params[:id]
    @selector = '.video_'+@video.id.to_s
  end

  def create
    if @video = Video.create(params[:video])
      @selector = '.video_'+@video.id.to_s
      respond_with(@video, :location => admin_root_url, :notice => 'Video successfully created')
    else
      respond_with(@video, :location => admin_root_url, :alert => 'Something went wrong')
    end
  end

  def update
    @video = Video.find params[:id]
    if @video.update_attributes(params[:video])
      @selector = '.video_'+@video.id.to_s
      respond_with(@video, :location => admin_root_url, :notice => 'Video successfully updated')
    else
      respond_with(@video, :location => admin_root_url)
    end
  end

  def destroy
    @video = Video.find params[:id]
    @video_id = '.video_'+ @video.id.to_s
    @video.destroy
  end

  def add_athlete
    unless @athlete = Athlete.find_by_name(params[:athlete])
      @athlete = Athlete.new(:name => params[:athlete])
    end
  end

end

app/helpers/video_helper.rb
module VideoHelper

  def fields_for_athlete(athlete, &block)
    prefix = athlete.new_record? ? 'new' : 'existing'
    haml_capture do
      fields_for("video[#{prefix}_athlete_attributes][]", athlete, &block)
    end
  end

  def determine_video_status(video)
    if video
      return video.status || 'active'
    elsif current_admin
      return 'active'
    else
      return 'inactive'
    end
  end

  def save_button(video)
    text = current_user ? (current_user.has_favorited(video) ? 'Saved' : 'Save') : 'Save'
    style = 'save_video ' + text.parameterize('_') + ' video_' + video.id.to_s
    capture_haml do
      haml_tag :a, {:href => favorite_path(video), :class => style, "data-remote" => "true" } do
        haml_tag :span, text, {:class => 'text'}
      end
    end
  end

  def watch_button(video)
    style = current_user ? ('watched' if current_user.has_viewed(video)) : ''
    capture_haml do
      haml_tag :a, 'Watch', {:href => watch_video_path(video), :class => style, "data-remote" => "true" }
    end
  end

end

app/views/videos/_form.html.haml
= lifted_box 'video_form' do
  = form_for video, :html => {:multipart => true} do |f|
    .head
      %h2 Video
      - if current_admin
        .status
          // todo: move to helper
          - status = determine_video_status(video)
          - VIDEO_STATES.each do |state|
            - selected = (status == state) ? 'selected' : ''
            - styles = 'status gray '+ state + ' ' + selected
            = bevel_button state, styles
          = hidden_field_tag 'video[status]', status
        .published_on
          =f.datetime_select 'published_at', :order => [:month, :day, :year]
      - else
        = hidden_field_tag 'video[status]', 'review'

    %span.hr
    .video
      = fancy_input 'video[title]', 'title', 'Title', video.title
      = fancy_input 'video[width]', 'width', '720', video.width
      = fancy_input 'video[height]', 'height', '405', video.height
      = fancy_input 'video[duration]', 'duration', 'Duration', video.duration
      .data
        = bevel_button 'embed', 'embed gray'
        .data_provider{:class => "#{'hide' if video.provider.blank? && !video.embed.blank? }" }
          = fancy_input 'video[provider]', 'provider', 'Provider', video.provider
          = fancy_input 'video[provider_id]', 'provider_id', 'Id', video.provider_id
        .data_embed{:class => "#{'hide' if video.embed.blank? }" }
          = fancy_input 'video[embed]', 'embed', 'Embed', video.embed
      = fancy_input 'video[source_url]', 'source', 'Source (url)', video.source_url
      = bevel_button 'image', 'image gray'
      .snapshot
        = f.file_field 'snapshot'
    %span.hr
    .athletes
      %h2 Starring
      = fancy_input 'riders', 'round icon athlete_search', 'Search / Add'
      %ul.tag_list
        - video.athletes.each do |athlete|
          = render 'athletes/tag_link', :athlete => athlete, :style => 'icon delete'
    %span.hr
    .buttons
      = f.submit 'submit', :class => 'hide'
      = bevel_button save_or_submit, 'done green submit'
      = bevel_button 'cancel', 'cancel gray'

%span.hr.with_video_form

app/views/videos/_video.html.haml
%li.video{ :class => "video_"+video.id.to_s }
  = link_to image_tag(video.snapshot.url), watch_video_path(video), :remote => true
  %span.duration= video.duration
  .info
    %h3= link_to video.title, watch_video_path(video), :remote => true
    .athletes
      %ul
        %li
          / %h4 Starring:
        - video.athletes.each do |athlete|
          - name = athlete.name
          - name += ', ' unless athlete == video.athletes.last
          %li= link_to name, athlete_path(athlete)
    // todo: there has to be a far better way to handle this
    %ul.meta
      - if video.source_url
        - if current_admin
          %li
            %span= video.status
            = " / "
        %li
          - unless video.source_url.blank?
            = link_to 'source', video.source_url, :target => '_blank'
            = " / "
      %li
        %span
          watched: 
          %span.total_views= video.total_views
          times /
      %li
        %span= "saves: #{video.favorites.count}"
        = " / "
      %li
        - past_or_future = video.published_at > Time.now ? 'from now' : 'ago' rescue nil
        %span= "posted #{distance_of_time_in_words_to_now video.published_at rescue nil} #{past_or_future}"
  %ul.options
    - unless current_admin
      // todo: if you haven't watched the video, mark it new
      %li.watch= watch_button(video)
      %li.save= save_button(video)
    - else
      %li.edit= link_to 'Edit', edit_video_path(video), :class => 'edit', :remote => true
      %li.delete= link_to 'Delete', video_path(video), :method => 'delete', :class => 'delete', :remote => true

app/views/videos/_watch.html.haml
.window.watch{:style => "width:#{@video.width}px; height:#{@video.height}px"}
  .player
    - if @video.provider.present?
      - case(@video.provider.parameterize('_'))
      - when 'vimeo' then p = 'vimeo'
      - when 'youtube' then p = 'youtube'  
    - else
      - p = 'code'

    = render 'videos/embed/' + p
    
  .panel.hoverable
    %h2= @video.title
    = save_button(@video)

app/views/videos/add_athlete.js.erb
// adds athletes to the new/edit video form
$("ul.tag_list").append("<%= escape_javascript(render(:partial => 'athletes/tag_link', :locals => {:athlete => @athlete, :style => 'icon delete'})) %>")

app/views/videos/destroy.js.erb
$("<%= escape_javascript(@video_id) %>").fadeOut('slow').remove()

app/views/videos/edit.js.erb
if ($("div.video_form")[0]) {
  video.form.hide()
}

$("<%= escape_javascript(@selector) %>").before("<%= escape_javascript(render(:partial => 'form', :locals => { :video => @video })) %>").fadeIn('fast')
video.form.init()

app/views/videos/list.html.haml
// head ----------------------------------------------------------------------

- content_for :on_ready do
  video.list.init()
  endless_page.init()

// body ----------------------------------------------------------------------

%ul.videos
  = render :partial =>'videos/video', :collection => @videos

app/views/videos/list.js.erb
$('ul.videos').append("<%= escape_javascript(render(:partial => 'videos/video', :collection => @videos)) %>")
video.list.init()

<% if @videos.total_pages > @videos.current_page %>
  endless_page.init()
<% end %>

app/views/videos/new.html.haml
%h1 NEW VIDEO FORM
= render :partial => 'form'

app/views/videos/new.js.erb
if ($("div.video_form")[0]) {
  video.form.hide()
} else {
  $("div.admin").hide().prepend("<%= escape_javascript(render(:partial => 'form', :locals => { :video => @video })) %>").fadeIn('fast')
  video.form.init()
}

app/views/videos/show.html.haml
// head ----------------------------------------------------------------------

- content_for :on_ready do
  video.list.init()
  = "video.popup.load('#{watch_video_path(@video)}')"


// body ----------------------------------------------------------------------

%ul.videos
  - @videos.each do |video|
    = render 'videos/video_item', :video => video

app/views/videos/show.js.erb
popup.render("<%= escape_javascript(render 'videos/watch', :video => @video) %>")

video.list.increment_views("<%= escape_javascript(@selector) %>")
video.popup.show()

app/views/videos/submit_link.js.erb
if ($("div.video_form")[0]) {
  video.form.hide()
} else {
  $("div.footer").before("<%= escape_javascript(render(:partial => 'form', :locals => { :video => @video })) %>")
  video.form.init()
}