config/routes.rb
Gondi::Application.routes.draw do |map|

  devise_for :admins
  devise_for :users

  resources :athletes

  match 'favorite/:id' => 'favorites#toggle', :as => 'favorite'
  match 'saves' => 'favorites#index', :as => 'favorites'

  match 'watch/:id' => 'videos#show', :as => 'watch_video'
  match 'videos/add_athlete' => 'videos#add_athlete'
  match 'submit_link' => 'videos#submit_link', :as => 'submit_link'
  resources :videos

  match 'admin', :to => 'admin#index', :as => 'admin_root'

  root :to => 'welcome#index'
  match 'info' => 'welcome#info', :as => 'info'

end

app/helpers/layout_helper.rb
module LayoutHelper

  # dirty hack to get rcov to see this
  def html_attrs(lang = 'en-US'); {:xmlns => "http://www.w3.org/1999/xhtml", 'xml:lang' => lang, :lang => lang}
  end

  def http_equiv_attrs
    {'http-equiv' => 'Content-Type', :content => 'text/html;charset=UTF-8'}
  end

  # allows for a default or custom page title
  # use: page_title('Artworks') # => ADMAC / Artworks
  def page_title
    title = @page_title ? "/ #{@page_title}" : ''
    content_tag(:title, 'GONDI.tv ' + title)
  end

  # allows specification of body class from view
  # use: page_style('two_column'), page_style('two_column green')
  def page_style(name)
    content_for(:page_style) { name }
  end

  # allows specification of view specific stylesheets
  # use: stylesheet('home')
  def stylesheet(*args)
    content_for(:stylesheets) { stylesheet_link_tag(*args) }
  end

  # allows specification of view specific javascripts
  # use: javascript('jquery.custom.plugin')
  def javascript(*args)
    args = *args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:javascripts) { javascript_include_tag()}
  end

  # outputs the corresponding flash message if set
  def flash_messages
    capture_haml do
      %w(notice alert).each do |msg|
        haml_tag :div, flash[msg.to_sym], :class => msg unless flash[msg.to_sym].blank?
      end
    end
  end








end

app/views/layouts/_admin.html.haml
- if current_admin
  .admin

app/views/layouts/_analytics.html.haml
// reinvigorate
= javascript_include_tag('http://include.reinvigorate.net/re_.js')
%script{ :type => 'text/javascript', :charset => 'utf-8' }
  try { reinvigorate.track("oz27y-0f83xg1b7a"); } catch(err) {}
  

// google analytics
%script{ :type => 'text/javascript', :charset => 'utf-8' }
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16211392-3']);
  _gaq.push(['_trackPageview']);

  (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  

app/views/layouts/_facebook.html.haml
#fb-root
= javascript_include_tag("http://connect.facebook.net/en_US/all.js")
%script{ :type => 'text/javascript', :charset => 'utf-8' }
  = "FB.init({ appId: '#{DeviseFacebookOpenGraph::Facebook::Config.application_id}', status: true, cookie: true, xfbml: true });"

app/views/layouts/_flash.html.haml
.flash
  = flash_messages

app/views/layouts/_footer.html.haml
.footer
  =link_to '© 2010 GONDI.TV', root_path, :class => 'copyright'
  %ul
    %li= link_to 'Info', info_path
    %li= link_to 'Submit Link', submit_link_path, :remote => true
    %li= mail_to 'team@gondi.tv', 'Contact', :subject => 'gondi.tv'

app/views/layouts/_gat.html.haml
- if RAILS_ENV == 'production'
  %script{ :type => 'text/javascript', :charset => 'utf-8' }
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-16211392-3']);
    _gaq.push(['_trackPageview']);

    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

app/views/layouts/_header.html.haml
.header
  .nav
    %ul
      - if current_admin
        %li
          = link_to 'new video', new_video_path, :remote => true, :class => 'new_video'
        %li= link_to 'sign out', destroy_admin_session_path, :title => current_admin.email
      - elsif current_user
        %li
          = link_to 'my saves', favorites_path, :class => 'my_saves'
        %li= link_to 'sign out', destroy_user_session_path, :title => current_user.email, :class => 'sign_out'
      - else
        %li
          = link_to 'sign in', new_user_session_path, :class => 'sign_in'
        %li= link_to 'Connect with Facebook', '#', :class => 'facebook'

  %h1= link_to @title, '/'

  // %span= videos_total(134)


  .search
    = fancy_input 'Search', 'round icon'

app/views/layouts/_javascripts.html.haml
// analytics
= render 'layouts/analytics'

// facebook
= render 'layouts/facebook'

// libraries todo: bundle/package
= javascript_include_tag "jquery/jquery","jquery/ui","jquery/autocomplete","jquery/hint"
= javascript_include_tag "/fonts/cufon","/fonts/gondvetica.font.js"
= javascript_include_tag "rails","patterns","popup","application"

// js from views
%script{ :type => 'text/javascript', :charset => 'utf-8' }
  $(document).ready(function() {
  = yield :on_ready
  })

app/views/layouts/_meta.html.haml
%meta{ http_equiv_attrs }
%meta{ 'http-equiv' => 'imagetoolbar', :content => 'no' }
%meta{ :name => 'distribution', :content => 'all' }
%meta{ :name => 'robots', :content => 'all' }
%meta{ :name => 'resource-type', :content => 'document' }
%meta{ :name => 'MSSmartTagsPreventParsing', :content => 'true' }

app/views/layouts/_popup.html.haml
#popup
  

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'application'

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml", "xmlns:fb" => "http://www.facebook.com/2008/fbml", :lang => "en", "xml:lang" => "en" }
  %head
    = page_title
    %link{ :rel => "shortcut icon", :href => "/images/favicon.ico" }
    = render :partial => 'layouts/meta'
    = render :partial => 'layouts/stylesheets'
    = csrf_meta_tag
    
  %body{ :class => yield(:page_style) }
    = render :partial => 'layouts/popup'
    .container
      = render :partial => 'layouts/header'
      %span.hr
      = render :partial => 'layouts/flash'
      = render :partial => 'layouts/admin'

      .content
        = yield :layout

      %span.hr

      = render :partial => 'layouts/footer'


    = render :partial => 'layouts/javascripts'